### ISSUE TITLE
requests should have timeout parameter set

### ISSUE THREAD

**Issue by newwaylw** [scaleapi/scaleapi-python-client#20]
as stated in the [requests API doc](https://requests.readthedocs.io/en/master/user/quickstart/#timeouts):
'''
Nearly all production code should use this parameter in nearly all requests. Failure to do so can cause your program to hang indefinitely:
'''
In the Scale Client class:
https://github.com/scaleapi/scaleapi-python-client/blob/a3fe4010327399dfcf220535150bad781620f41f/scaleapi/__init__.py#L94

No timeout value is set or exposed, this may leave the caller hang in forever for a timeout

**Comment by fatihkurtoglu** [comment]
Currently, our SDK depends on the Scale API endpoint for the timeout duration and doesn't enforce any timeout on the client-side.

With the new released v2, SDK now supports HTTP Retry with back-off in order to retry in case of timeout occurs. In case of any connection problem occurs due to the local network, it returns an error after three trials, without hanging forever.
